### PR TITLE
Fix machine warnings

### LINKED ISSUE #146: Fix machine warning
Fix console warning
`Machine given to "useMachine" has changed between renders. This is not supported and might lead to unexpected results.
Please make sure that you pass the same Machine as argument each time.`

### PR DESCRIPTION
**Pull request by cs-balazs**
Closes #146

### CODE REVIEW

**Comment by cs-balazs** [comment]
For some reason, this warning does not show up for me, but it did at drop.app, so I just did the same thing here.
Let me know if it fixed the warnings for you.

File: src/hooks/useSubmit/useSubmit.ts [hunk 1]
```diff
@@ -11,7 +12,8 @@ const useSubmit = <DataType, ResponseType>(
   fetch: (data: DataType) => Promise<ResponseType>,
   { onSuccess, onError }: Options<ResponseType> = {}
 ) => {
-  const [state, send] = useMachine(createFetchMachine<DataType, ResponseType>(), {
+  const machine = useRef(createFetchMachine<DataType, ResponseType>())
```
Comment (dovalid) [inline src/hooks/useSubmit/useSubmit.ts:15]: Could we add a comment here noting why it's necessary?

**Review by dovalid — APPROVED** [review]
